bitly:
  username: "diactionman"
  api_key: "R_dedfe79fe375266f668a1cb1ee050ae1"
android:
  host: "http://qa.actionman.zerobot.io"
development:
  host: "http://qa.actionman.zerobot.io"
production:
  host: "http://production.actionman.zerobot.io"
  analytics_tracking_key: "UA-39769967-1"
qa:
  host: "http://qa.actionman.zerobot.io"
qa_mobile_assets:
  host: "http://qa.actionman.zerobot.io"
test:
  host: "http://poo.actionman.zerobot.io"

